//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using Limnor.Drawing2D;
    using System.Drawing;
    using System.Windows.Forms;
    
    public class Form2 : Limnor.Drawing2D.DrawingPage
    {
        protected internal System.Windows.Forms.Label Label1;
        protected internal System.Windows.Forms.PictureBox PictureBox1;
        protected internal System.Windows.Forms.Label Label2;
        protected internal System.Windows.Forms.Label Label3;
        protected internal System.Windows.Forms.TextBox TextBox1;
        protected internal System.Windows.Forms.TextBox TextBox2;
        protected internal System.Windows.Forms.Button Button1;
        protected internal DefaultNamespace.Task vare3211ea1;
        private static Form2 _DefaultForm;
        /// <summary>
        /// </summary>
        public Form2()
        {
            this.InitializeComponent();
        }
        public static Form2 DefaultForm
        {
            get
            {
                if (((_DefaultForm == null) 
                            || (_DefaultForm.IsDisposed || _DefaultForm.Disposing)))
                {
                    _DefaultForm = new Form2();
                }
                return _DefaultForm;
            }
        }
        public virtual DefaultNamespace.Task Task2
        {
            get
            {
                if (((vare3211ea1 == null) 
                            || (vare3211ea1.IsDisposed == true)))
                {
                    vare3211ea1 = new DefaultNamespace.Task();
                }
                return vare3211ea1;
            }
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form2));
            this.Label1 = new System.Windows.Forms.Label();
            this.PictureBox1 = new System.Windows.Forms.PictureBox();
            this.Label2 = new System.Windows.Forms.Label();
            this.Label3 = new System.Windows.Forms.Label();
            this.TextBox1 = new System.Windows.Forms.TextBox();
            this.TextBox2 = new System.Windows.Forms.TextBox();
            this.Button1 = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(PictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // Label1
            // 
            this.Label1.Font = new System.Drawing.Font("Comic Sans MS", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Label1.ForeColor = System.Drawing.SystemColors.Desktop;
            this.Label1.Location = new System.Drawing.Point(82, 9);
            this.Label1.Name = "Label1";
            this.Label1.Size = new System.Drawing.Size(100, 23);
            this.Label1.TabIndex = 0;
            this.Label1.Text = "    Login ";
            // 
            // PictureBox1
            // 
            this.PictureBox1.ErrorImage = ((System.Drawing.Image)(resources.GetObject("PictureBox1.ErrorImage")));
            this.PictureBox1.ImageLocation = "picture";
            this.PictureBox1.InitialImage = ((System.Drawing.Image)(resources.GetObject("PictureBox1.InitialImage")));
            this.PictureBox1.Location = new System.Drawing.Point(98, 35);
            this.PictureBox1.Name = "PictureBox1";
            this.PictureBox1.Size = new System.Drawing.Size(72, 50);
            this.PictureBox1.TabIndex = 5;
            this.PictureBox1.TabStop = false;
            // 
            // Label2
            // 
            this.Label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Label2.ForeColor = System.Drawing.SystemColors.Desktop;
            this.Label2.Location = new System.Drawing.Point(23, 104);
            this.Label2.Name = "Label2";
            this.Label2.Size = new System.Drawing.Size(100, 23);
            this.Label2.TabIndex = 1;
            this.Label2.Text = "UserName";
            // 
            // Label3
            // 
            this.Label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Label3.ForeColor = System.Drawing.SystemColors.Desktop;
            this.Label3.Location = new System.Drawing.Point(23, 156);
            this.Label3.Name = "Label3";
            this.Label3.Size = new System.Drawing.Size(100, 23);
            this.Label3.TabIndex = 2;
            this.Label3.Text = "Password";
            // 
            // TextBox1
            // 
            this.TextBox1.Location = new System.Drawing.Point(147, 108);
            this.TextBox1.Name = "TextBox1";
            this.TextBox1.Size = new System.Drawing.Size(123, 20);
            this.TextBox1.TabIndex = 3;
            // 
            // TextBox2
            // 
            this.TextBox2.Location = new System.Drawing.Point(147, 156);
            this.TextBox2.Name = "TextBox2";
            this.TextBox2.Size = new System.Drawing.Size(123, 20);
            this.TextBox2.TabIndex = 4;
            // 
            // Button1
            // 
            this.Button1.Location = new System.Drawing.Point(71, 200);
            this.Button1.Name = "Button1";
            this.Button1.Size = new System.Drawing.Size(122, 23);
            this.Button1.TabIndex = 6;
            this.Button1.Text = "Save and Next";
            this.Button1.UseVisualStyleBackColor = true;
            this.Button1.Click += new System.EventHandler(this.Click_f6cfd1e3);
            // 
            // Task2
            // 
            this.Task2.LoginPage = null;
            this.Task2.PageAttributes.Height = 297D;
            this.Task2.PageAttributes.PageHeight = 1122.51968503937D;
            this.Task2.PageAttributes.PageWidth = 793.70078740157476D;
            this.Task2.PageAttributes.PrinterDPI_X = 96F;
            this.Task2.PageAttributes.PrinterDPI_Y = 96F;
            this.Task2.PageAttributes.ShowPrintPageEdges = false;
            this.Task2.PageAttributes.Width = 210D;
            this.Task2.Text = "DrawingPage";
            this.Task2.UserLevel = 0;
            this.Task2.Visible = false;
            // 
            // Form2
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.ClientSize = new System.Drawing.Size(282, 257);
            this.Controls.Add(this.Label1);
            this.Controls.Add(this.PictureBox1);
            this.Controls.Add(this.Label2);
            this.Controls.Add(this.Label3);
            this.Controls.Add(this.TextBox1);
            this.Controls.Add(this.TextBox2);
            this.Controls.Add(this.Button1);
            this.DrawingLayerList = ((Limnor.Drawing2D.DrawingLayerHeaderList)(resources.GetObject("$this.DrawingLayerList")));
            this.Name = "Form2";
            this.Text = "Login";
            ((System.ComponentModel.ISupportInitialize)(PictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private void Click_f6cfd1e3(object sender, System.EventArgs e)
        {
            Task2.Show();
        }
    }
}
