//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using Limnor.Drawing2D;
    using System.Drawing;
    using System.Windows.Forms;
    
    public class Form4 : Limnor.Drawing2D.DrawingPage
    {
        protected internal System.Windows.Forms.DateTimePicker DateTimePicker1;
        protected internal System.Windows.Forms.Label Label1;
        protected internal System.Windows.Forms.CheckBox CheckBox4;
        protected internal System.Windows.Forms.CheckBox CheckBox2;
        protected internal System.Windows.Forms.CheckBox CheckBox1;
        protected internal System.Windows.Forms.CheckBox CheckBox3;
        protected internal System.Windows.Forms.Label Label2;
        protected internal System.Windows.Forms.TextBox TextBox1;
        protected internal System.Windows.Forms.Button Button1;
        protected internal DefaultNamespace.Form5 var715eff3f;
        private static Form4 _DefaultForm;
        /// <summary>
        /// </summary>
        public Form4()
        {
            this.InitializeComponent();
        }
        public static Form4 DefaultForm
        {
            get
            {
                if (((_DefaultForm == null) 
                            || (_DefaultForm.IsDisposed || _DefaultForm.Disposing)))
                {
                    _DefaultForm = new Form4();
                }
                return _DefaultForm;
            }
        }
        public virtual DefaultNamespace.Form5 Form52
        {
            get
            {
                if (((var715eff3f == null) 
                            || (var715eff3f.IsDisposed == true)))
                {
                    var715eff3f = new DefaultNamespace.Form5();
                }
                return var715eff3f;
            }
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form4));
            this.DateTimePicker1 = new System.Windows.Forms.DateTimePicker();
            this.Label1 = new System.Windows.Forms.Label();
            this.CheckBox4 = new System.Windows.Forms.CheckBox();
            this.CheckBox2 = new System.Windows.Forms.CheckBox();
            this.CheckBox1 = new System.Windows.Forms.CheckBox();
            this.CheckBox3 = new System.Windows.Forms.CheckBox();
            this.Label2 = new System.Windows.Forms.Label();
            this.TextBox1 = new System.Windows.Forms.TextBox();
            this.Button1 = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // DateTimePicker1
            // 
            this.DateTimePicker1.Location = new System.Drawing.Point(82, -1);
            this.DateTimePicker1.Name = "DateTimePicker1";
            this.DateTimePicker1.Size = new System.Drawing.Size(200, 20);
            this.DateTimePicker1.TabIndex = 5;
            // 
            // Label1
            // 
            this.Label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Label1.ForeColor = System.Drawing.SystemColors.Desktop;
            this.Label1.Location = new System.Drawing.Point(34, 34);
            this.Label1.Name = "Label1";
            this.Label1.Size = new System.Drawing.Size(198, 32);
            this.Label1.TabIndex = 0;
            this.Label1.Text = "Dimensions in inches";
            // 
            // CheckBox4
            // 
            this.CheckBox4.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.CheckBox4.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.CheckBox4.Location = new System.Drawing.Point(22, 69);
            this.CheckBox4.Name = "CheckBox4";
            this.CheckBox4.Size = new System.Drawing.Size(104, 24);
            this.CheckBox4.TabIndex = 1;
            this.CheckBox4.Text = "1-3 inches";
            this.CheckBox4.UseVisualStyleBackColor = true;
            // 
            // CheckBox2
            // 
            this.CheckBox2.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.CheckBox2.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.CheckBox2.Location = new System.Drawing.Point(22, 121);
            this.CheckBox2.Name = "CheckBox2";
            this.CheckBox2.Size = new System.Drawing.Size(104, 24);
            this.CheckBox2.TabIndex = 1;
            this.CheckBox2.Text = "6-9 inches";
            this.CheckBox2.UseVisualStyleBackColor = true;
            // 
            // CheckBox1
            // 
            this.CheckBox1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.CheckBox1.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.CheckBox1.Location = new System.Drawing.Point(157, 69);
            this.CheckBox1.Name = "CheckBox1";
            this.CheckBox1.Size = new System.Drawing.Size(104, 24);
            this.CheckBox1.TabIndex = 1;
            this.CheckBox1.Text = "3-6 inches";
            this.CheckBox1.UseVisualStyleBackColor = true;
            // 
            // CheckBox3
            // 
            this.CheckBox3.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.CheckBox3.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.CheckBox3.Location = new System.Drawing.Point(157, 121);
            this.CheckBox3.Name = "CheckBox3";
            this.CheckBox3.Size = new System.Drawing.Size(104, 24);
            this.CheckBox3.TabIndex = 1;
            this.CheckBox3.Text = "9-12 inches";
            this.CheckBox3.UseVisualStyleBackColor = true;
            // 
            // Label2
            // 
            this.Label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.Label2.Location = new System.Drawing.Point(12, 175);
            this.Label2.Name = "Label2";
            this.Label2.Size = new System.Drawing.Size(125, 23);
            this.Label2.TabIndex = 2;
            this.Label2.Text = "If other then specify";
            // 
            // TextBox1
            // 
            this.TextBox1.Location = new System.Drawing.Point(157, 174);
            this.TextBox1.Name = "TextBox1";
            this.TextBox1.Size = new System.Drawing.Size(100, 20);
            this.TextBox1.TabIndex = 3;
            // 
            // Button1
            // 
            this.Button1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Button1.Location = new System.Drawing.Point(82, 222);
            this.Button1.Name = "Button1";
            this.Button1.Size = new System.Drawing.Size(129, 23);
            this.Button1.TabIndex = 6;
            this.Button1.Text = "Save and Next";
            this.Button1.UseVisualStyleBackColor = true;
            this.Button1.Click += new System.EventHandler(this.Click_b472178f);
            // 
            // Form52
            // 
            this.Form52.LoginPage = null;
            this.Form52.PageAttributes.Height = 297D;
            this.Form52.PageAttributes.PageHeight = 1122.51968503937D;
            this.Form52.PageAttributes.PageWidth = 793.70078740157476D;
            this.Form52.PageAttributes.PrinterDPI_X = 96F;
            this.Form52.PageAttributes.PrinterDPI_Y = 96F;
            this.Form52.PageAttributes.ShowPrintPageEdges = false;
            this.Form52.PageAttributes.Width = 210D;
            this.Form52.Text = "DrawingPage";
            this.Form52.UserLevel = 0;
            this.Form52.Visible = false;
            // 
            // Form4
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.ClientSize = new System.Drawing.Size(282, 257);
            this.Controls.Add(this.DateTimePicker1);
            this.Controls.Add(this.Label1);
            this.Controls.Add(this.CheckBox4);
            this.Controls.Add(this.CheckBox2);
            this.Controls.Add(this.CheckBox1);
            this.Controls.Add(this.CheckBox3);
            this.Controls.Add(this.Label2);
            this.Controls.Add(this.TextBox1);
            this.Controls.Add(this.Button1);
            this.DrawingLayerList = ((Limnor.Drawing2D.DrawingLayerHeaderList)(resources.GetObject("$this.DrawingLayerList")));
            this.Name = "Form4";
            this.Text = "Dimensions";
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private void Click_b472178f(object sender, System.EventArgs e)
        {
            Form52.Show();
        }
    }
}
