//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using Limnor.Drawing2D;
    using System.Drawing;
    using System.Windows.Forms;
    
    public class Form5 : Limnor.Drawing2D.DrawingPage
    {
        protected internal System.Windows.Forms.Label Label1;
        protected internal System.Windows.Forms.CheckBox CheckBox1;
        protected internal System.Windows.Forms.CheckBox CheckBox2;
        protected internal System.Windows.Forms.CheckBox CheckBox3;
        protected internal System.Windows.Forms.Button Button1;
        private static Form5 _DefaultForm;
        /// <summary>
        /// </summary>
        public Form5()
        {
            this.InitializeComponent();
        }
        public static Form5 DefaultForm
        {
            get
            {
                if (((_DefaultForm == null) 
                            || (_DefaultForm.IsDisposed || _DefaultForm.Disposing)))
                {
                    _DefaultForm = new Form5();
                }
                return _DefaultForm;
            }
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form5));
            this.Label1 = new System.Windows.Forms.Label();
            this.CheckBox1 = new System.Windows.Forms.CheckBox();
            this.CheckBox2 = new System.Windows.Forms.CheckBox();
            this.CheckBox3 = new System.Windows.Forms.CheckBox();
            this.Button1 = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // Label1
            // 
            this.Label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Label1.Location = new System.Drawing.Point(87, 24);
            this.Label1.Name = "Label1";
            this.Label1.Size = new System.Drawing.Size(100, 23);
            this.Label1.TabIndex = 0;
            this.Label1.Text = "Review";
            // 
            // CheckBox1
            // 
            this.CheckBox1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.CheckBox1.Location = new System.Drawing.Point(87, 115);
            this.CheckBox1.Name = "CheckBox1";
            this.CheckBox1.Size = new System.Drawing.Size(104, 24);
            this.CheckBox1.TabIndex = 1;
            this.CheckBox1.Text = "AVERAGE";
            this.CheckBox1.UseVisualStyleBackColor = true;
            // 
            // CheckBox2
            // 
            this.CheckBox2.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.CheckBox2.Location = new System.Drawing.Point(25, 85);
            this.CheckBox2.Name = "CheckBox2";
            this.CheckBox2.Size = new System.Drawing.Size(104, 24);
            this.CheckBox2.TabIndex = 1;
            this.CheckBox2.Text = "GOOD";
            this.CheckBox2.UseVisualStyleBackColor = true;
            // 
            // CheckBox3
            // 
            this.CheckBox3.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.CheckBox3.Location = new System.Drawing.Point(182, 85);
            this.CheckBox3.Name = "CheckBox3";
            this.CheckBox3.Size = new System.Drawing.Size(104, 24);
            this.CheckBox3.TabIndex = 1;
            this.CheckBox3.Text = "BAD";
            this.CheckBox3.UseVisualStyleBackColor = true;
            // 
            // Button1
            // 
            this.Button1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Button1.Location = new System.Drawing.Point(77, 174);
            this.Button1.Name = "Button1";
            this.Button1.Size = new System.Drawing.Size(131, 34);
            this.Button1.TabIndex = 2;
            this.Button1.Text = "Submit";
            this.Button1.UseVisualStyleBackColor = true;
            this.Button1.Click += new System.EventHandler(this.Click_a6e5ce22);
            // 
            // Form5
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.ClientSize = new System.Drawing.Size(282, 257);
            this.Controls.Add(this.Label1);
            this.Controls.Add(this.CheckBox1);
            this.Controls.Add(this.CheckBox2);
            this.Controls.Add(this.CheckBox3);
            this.Controls.Add(this.Button1);
            this.DrawingLayerList = ((Limnor.Drawing2D.DrawingLayerHeaderList)(resources.GetObject("$this.DrawingLayerList")));
            this.Name = "Form5";
            this.Text = "Submit";
            this.ResumeLayout(false);
            this.Click += new System.EventHandler(this.Click_62177f17);
        }
        private void Click_62177f17(object sender, System.EventArgs e)
        {
            this.Button1.Text = "THANKYOU";
        }
        private void Click_a6e5ce22(object sender, System.EventArgs e)
        {
            this.Button1.Text = "THANKYOU";
        }
    }
}
