//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using Limnor.Drawing2D;
    using System.Drawing;
    using System.Windows.Forms;
    
    public class Form3 : Limnor.Drawing2D.DrawingPage
    {
        protected internal System.Windows.Forms.Label Label1;
        protected internal System.Windows.Forms.PictureBox PictureBox1;
        protected internal System.Windows.Forms.Label Label3;
        protected internal System.Windows.Forms.Label Label2;
        protected internal System.Windows.Forms.Label Label4;
        protected internal System.Windows.Forms.Label Label5;
        protected internal System.Windows.Forms.TextBox TextBox4;
        protected internal System.Windows.Forms.TextBox TextBox1;
        protected internal System.Windows.Forms.TextBox TextBox2;
        protected internal System.Windows.Forms.TextBox TextBox3;
        protected internal System.Windows.Forms.Button Button1;
        protected internal DefaultNamespace.Task varc44f0a48;
        private static Form3 _DefaultForm;
        /// <summary>
        /// </summary>
        public Form3()
        {
            this.InitializeComponent();
        }
        public static Form3 DefaultForm
        {
            get
            {
                if (((_DefaultForm == null) 
                            || (_DefaultForm.IsDisposed || _DefaultForm.Disposing)))
                {
                    _DefaultForm = new Form3();
                }
                return _DefaultForm;
            }
        }
        public virtual DefaultNamespace.Task Task2
        {
            get
            {
                if (((varc44f0a48 == null) 
                            || (varc44f0a48.IsDisposed == true)))
                {
                    varc44f0a48 = new DefaultNamespace.Task();
                }
                return varc44f0a48;
            }
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form3));
            this.Label1 = new System.Windows.Forms.Label();
            this.PictureBox1 = new System.Windows.Forms.PictureBox();
            this.Label3 = new System.Windows.Forms.Label();
            this.Label2 = new System.Windows.Forms.Label();
            this.Label4 = new System.Windows.Forms.Label();
            this.Label5 = new System.Windows.Forms.Label();
            this.TextBox4 = new System.Windows.Forms.TextBox();
            this.TextBox1 = new System.Windows.Forms.TextBox();
            this.TextBox2 = new System.Windows.Forms.TextBox();
            this.TextBox3 = new System.Windows.Forms.TextBox();
            this.Button1 = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(PictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // Label1
            // 
            this.Label1.Font = new System.Drawing.Font("Algerian", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Label1.ForeColor = System.Drawing.SystemColors.Desktop;
            this.Label1.Location = new System.Drawing.Point(169, 9);
            this.Label1.Name = "Label1";
            this.Label1.Size = new System.Drawing.Size(100, 23);
            this.Label1.TabIndex = 0;
            this.Label1.Text = "   SignUp";
            // 
            // PictureBox1
            // 
            this.PictureBox1.ErrorImage = ((System.Drawing.Image)(resources.GetObject("PictureBox1.ErrorImage")));
            this.PictureBox1.ImageLocation = "picture1";
            this.PictureBox1.InitialImage = ((System.Drawing.Image)(resources.GetObject("PictureBox1.InitialImage")));
            this.PictureBox1.Location = new System.Drawing.Point(169, 35);
            this.PictureBox1.Name = "PictureBox1";
            this.PictureBox1.Size = new System.Drawing.Size(100, 61);
            this.PictureBox1.TabIndex = 2;
            this.PictureBox1.TabStop = false;
            // 
            // Label3
            // 
            this.Label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Label3.ForeColor = System.Drawing.SystemColors.Desktop;
            this.Label3.Location = new System.Drawing.Point(67, 141);
            this.Label3.Name = "Label3";
            this.Label3.Size = new System.Drawing.Size(100, 23);
            this.Label3.TabIndex = 1;
            this.Label3.Text = "Name";
            // 
            // Label2
            // 
            this.Label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Label2.ForeColor = System.Drawing.SystemColors.Desktop;
            this.Label2.Location = new System.Drawing.Point(67, 173);
            this.Label2.Name = "Label2";
            this.Label2.Size = new System.Drawing.Size(100, 23);
            this.Label2.TabIndex = 1;
            this.Label2.Text = "Address";
            // 
            // Label4
            // 
            this.Label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Label4.ForeColor = System.Drawing.SystemColors.Desktop;
            this.Label4.Location = new System.Drawing.Point(67, 205);
            this.Label4.Name = "Label4";
            this.Label4.Size = new System.Drawing.Size(100, 23);
            this.Label4.TabIndex = 1;
            this.Label4.Text = "Contact No.";
            // 
            // Label5
            // 
            this.Label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Label5.ForeColor = System.Drawing.SystemColors.Desktop;
            this.Label5.Location = new System.Drawing.Point(67, 237);
            this.Label5.Name = "Label5";
            this.Label5.Size = new System.Drawing.Size(100, 23);
            this.Label5.TabIndex = 1;
            this.Label5.Text = "Password";
            // 
            // TextBox4
            // 
            this.TextBox4.Location = new System.Drawing.Point(248, 141);
            this.TextBox4.Name = "TextBox4";
            this.TextBox4.Size = new System.Drawing.Size(155, 20);
            this.TextBox4.TabIndex = 3;
            // 
            // TextBox1
            // 
            this.TextBox1.Location = new System.Drawing.Point(248, 174);
            this.TextBox1.Name = "TextBox1";
            this.TextBox1.Size = new System.Drawing.Size(155, 20);
            this.TextBox1.TabIndex = 3;
            // 
            // TextBox2
            // 
            this.TextBox2.Location = new System.Drawing.Point(248, 208);
            this.TextBox2.Name = "TextBox2";
            this.TextBox2.Size = new System.Drawing.Size(155, 20);
            this.TextBox2.TabIndex = 3;
            // 
            // TextBox3
            // 
            this.TextBox3.Location = new System.Drawing.Point(248, 240);
            this.TextBox3.Name = "TextBox3";
            this.TextBox3.Size = new System.Drawing.Size(155, 20);
            this.TextBox3.TabIndex = 3;
            // 
            // Button1
            // 
            this.Button1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Button1.Location = new System.Drawing.Point(155, 281);
            this.Button1.Name = "Button1";
            this.Button1.Size = new System.Drawing.Size(134, 23);
            this.Button1.TabIndex = 4;
            this.Button1.Text = "Save and Next ";
            this.Button1.UseVisualStyleBackColor = true;
            this.Button1.Click += new System.EventHandler(this.Click_7eae4fee);
            // 
            // Task2
            // 
            this.Task2.LoginPage = null;
            this.Task2.PageAttributes.Height = 297D;
            this.Task2.PageAttributes.PageHeight = 1122.51968503937D;
            this.Task2.PageAttributes.PageWidth = 793.70078740157476D;
            this.Task2.PageAttributes.PrinterDPI_X = 96F;
            this.Task2.PageAttributes.PrinterDPI_Y = 96F;
            this.Task2.PageAttributes.ShowPrintPageEdges = false;
            this.Task2.PageAttributes.Width = 210D;
            this.Task2.Text = "DrawingPage";
            this.Task2.UserLevel = 0;
            this.Task2.Visible = false;
            // 
            // Form3
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.ClientSize = new System.Drawing.Size(422, 316);
            this.Controls.Add(this.Label1);
            this.Controls.Add(this.PictureBox1);
            this.Controls.Add(this.Label3);
            this.Controls.Add(this.Label2);
            this.Controls.Add(this.Label4);
            this.Controls.Add(this.Label5);
            this.Controls.Add(this.TextBox4);
            this.Controls.Add(this.TextBox1);
            this.Controls.Add(this.TextBox2);
            this.Controls.Add(this.TextBox3);
            this.Controls.Add(this.Button1);
            this.DrawingLayerList = ((Limnor.Drawing2D.DrawingLayerHeaderList)(resources.GetObject("$this.DrawingLayerList")));
            this.Name = "Form3";
            this.Text = "SignUp";
            ((System.ComponentModel.ISupportInitialize)(PictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private void Click_7eae4fee(object sender, System.EventArgs e)
        {
            Task2.Show();
        }
    }
}
