//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using Limnor.Drawing2D;
    using System.Drawing;
    using System.Windows.Forms;
    
    public class Task : Limnor.Drawing2D.DrawingPage
    {
        protected internal System.Windows.Forms.DateTimePicker DateTimePicker1;
        protected internal System.Windows.Forms.Label Label1;
        protected internal System.Windows.Forms.PictureBox PictureBox3;
        protected internal System.Windows.Forms.CheckBox CheckBox3;
        protected internal System.Windows.Forms.PictureBox PictureBox2;
        protected internal System.Windows.Forms.CheckBox CheckBox2;
        protected internal System.Windows.Forms.PictureBox PictureBox1;
        protected internal System.Windows.Forms.CheckBox CheckBox1;
        protected internal System.Windows.Forms.Button Button1;
        protected internal DefaultNamespace.Form4 vare0e63470;
        private static Task _DefaultForm;
        /// <summary>
        /// </summary>
        public Task()
        {
            this.InitializeComponent();
        }
        public static Task DefaultForm
        {
            get
            {
                if (((_DefaultForm == null) 
                            || (_DefaultForm.IsDisposed || _DefaultForm.Disposing)))
                {
                    _DefaultForm = new Task();
                }
                return _DefaultForm;
            }
        }
        public virtual DefaultNamespace.Form4 Form42
        {
            get
            {
                if (((vare0e63470 == null) 
                            || (vare0e63470.IsDisposed == true)))
                {
                    vare0e63470 = new DefaultNamespace.Form4();
                }
                return vare0e63470;
            }
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Task));
            this.DateTimePicker1 = new System.Windows.Forms.DateTimePicker();
            this.Label1 = new System.Windows.Forms.Label();
            this.PictureBox3 = new System.Windows.Forms.PictureBox();
            this.CheckBox3 = new System.Windows.Forms.CheckBox();
            this.PictureBox2 = new System.Windows.Forms.PictureBox();
            this.CheckBox2 = new System.Windows.Forms.CheckBox();
            this.PictureBox1 = new System.Windows.Forms.PictureBox();
            this.CheckBox1 = new System.Windows.Forms.CheckBox();
            this.Button1 = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(PictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(PictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(PictureBox3)).BeginInit();
            this.SuspendLayout();
            // 
            // DateTimePicker1
            // 
            this.DateTimePicker1.Location = new System.Drawing.Point(137, -1);
            this.DateTimePicker1.Name = "DateTimePicker1";
            this.DateTimePicker1.Size = new System.Drawing.Size(200, 20);
            this.DateTimePicker1.TabIndex = 4;
            // 
            // Label1
            // 
            this.Label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Label1.ForeColor = System.Drawing.SystemColors.Desktop;
            this.Label1.Location = new System.Drawing.Point(92, 40);
            this.Label1.Name = "Label1";
            this.Label1.Size = new System.Drawing.Size(164, 23);
            this.Label1.TabIndex = 0;
            this.Label1.Text = "   Type Of Task";
            // 
            // PictureBox3
            // 
            this.PictureBox3.ErrorImage = ((System.Drawing.Image)(resources.GetObject("PictureBox3.ErrorImage")));
            this.PictureBox3.ImageLocation = "pic1";
            this.PictureBox3.InitialImage = ((System.Drawing.Image)(resources.GetObject("PictureBox3.InitialImage")));
            this.PictureBox3.Location = new System.Drawing.Point(16, 80);
            this.PictureBox3.Name = "PictureBox3";
            this.PictureBox3.Size = new System.Drawing.Size(100, 50);
            this.PictureBox3.TabIndex = 1;
            this.PictureBox3.TabStop = false;
            // 
            // CheckBox3
            // 
            this.CheckBox3.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.CheckBox3.ForeColor = System.Drawing.SystemColors.Desktop;
            this.CheckBox3.Location = new System.Drawing.Point(16, 136);
            this.CheckBox3.Name = "CheckBox3";
            this.CheckBox3.Size = new System.Drawing.Size(104, 24);
            this.CheckBox3.TabIndex = 2;
            this.CheckBox3.Text = "Grinding";
            this.CheckBox3.UseVisualStyleBackColor = true;
            // 
            // PictureBox2
            // 
            this.PictureBox2.ErrorImage = ((System.Drawing.Image)(resources.GetObject("PictureBox2.ErrorImage")));
            this.PictureBox2.ImageLocation = "pic3";
            this.PictureBox2.InitialImage = ((System.Drawing.Image)(resources.GetObject("PictureBox2.InitialImage")));
            this.PictureBox2.Location = new System.Drawing.Point(105, 166);
            this.PictureBox2.Name = "PictureBox2";
            this.PictureBox2.Size = new System.Drawing.Size(100, 50);
            this.PictureBox2.TabIndex = 1;
            this.PictureBox2.TabStop = false;
            // 
            // CheckBox2
            // 
            this.CheckBox2.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.CheckBox2.ForeColor = System.Drawing.SystemColors.Desktop;
            this.CheckBox2.Location = new System.Drawing.Point(105, 222);
            this.CheckBox2.Name = "CheckBox2";
            this.CheckBox2.Size = new System.Drawing.Size(104, 24);
            this.CheckBox2.TabIndex = 2;
            this.CheckBox2.Text = "Purchase";
            this.CheckBox2.UseVisualStyleBackColor = true;
            // 
            // PictureBox1
            // 
            this.PictureBox1.ErrorImage = ((System.Drawing.Image)(resources.GetObject("PictureBox1.ErrorImage")));
            this.PictureBox1.ImageLocation = "pic2";
            this.PictureBox1.InitialImage = ((System.Drawing.Image)(resources.GetObject("PictureBox1.InitialImage")));
            this.PictureBox1.Location = new System.Drawing.Point(185, 80);
            this.PictureBox1.Name = "PictureBox1";
            this.PictureBox1.Size = new System.Drawing.Size(100, 50);
            this.PictureBox1.TabIndex = 1;
            this.PictureBox1.TabStop = false;
            // 
            // CheckBox1
            // 
            this.CheckBox1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.CheckBox1.ForeColor = System.Drawing.SystemColors.Desktop;
            this.CheckBox1.Location = new System.Drawing.Point(185, 136);
            this.CheckBox1.Name = "CheckBox1";
            this.CheckBox1.Size = new System.Drawing.Size(104, 24);
            this.CheckBox1.TabIndex = 2;
            this.CheckBox1.Text = "Cutting";
            this.CheckBox1.UseVisualStyleBackColor = true;
            // 
            // Button1
            // 
            this.Button1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Button1.Location = new System.Drawing.Point(92, 267);
            this.Button1.Name = "Button1";
            this.Button1.Size = new System.Drawing.Size(138, 23);
            this.Button1.TabIndex = 5;
            this.Button1.Text = "Save and Next";
            this.Button1.UseVisualStyleBackColor = true;
            this.Button1.Click += new System.EventHandler(this.Click_75a168d7);
            // 
            // Form42
            // 
            this.Form42.LoginPage = null;
            this.Form42.PageAttributes.Height = 297D;
            this.Form42.PageAttributes.PageHeight = 1122.51968503937D;
            this.Form42.PageAttributes.PageWidth = 793.70078740157476D;
            this.Form42.PageAttributes.PrinterDPI_X = 96F;
            this.Form42.PageAttributes.PrinterDPI_Y = 96F;
            this.Form42.PageAttributes.ShowPrintPageEdges = false;
            this.Form42.PageAttributes.Width = 210D;
            this.Form42.Text = "DrawingPage";
            this.Form42.UserLevel = 0;
            this.Form42.Visible = false;
            // 
            // Task
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.ClientSize = new System.Drawing.Size(332, 302);
            this.Controls.Add(this.DateTimePicker1);
            this.Controls.Add(this.Label1);
            this.Controls.Add(this.PictureBox3);
            this.Controls.Add(this.CheckBox3);
            this.Controls.Add(this.PictureBox2);
            this.Controls.Add(this.CheckBox2);
            this.Controls.Add(this.PictureBox1);
            this.Controls.Add(this.CheckBox1);
            this.Controls.Add(this.Button1);
            this.DrawingLayerList = ((Limnor.Drawing2D.DrawingLayerHeaderList)(resources.GetObject("$this.DrawingLayerList")));
            this.Name = "Task";
            this.Text = "Task";
            ((System.ComponentModel.ISupportInitialize)(PictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(PictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(PictureBox3)).EndInit();
            this.ResumeLayout(false);
        }
        private void Click_75a168d7(object sender, System.EventArgs e)
        {
            Form42.Show();
        }
    }
}
