//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using Limnor.Drawing2D;
    using System.Drawing;
    using System.Windows.Forms;
    
    public class Form1 : Limnor.Drawing2D.DrawingPage
    {
        protected internal System.Windows.Forms.Label Label1;
        protected internal System.Windows.Forms.Label Label2;
        protected internal System.Windows.Forms.Label Label3;
        protected internal System.Windows.Forms.Button Button1;
        protected internal System.Windows.Forms.Button Button2;
        protected internal DefaultNamespace.Form2 var16f4a848;
        protected internal DefaultNamespace.Form3 varc80ef335;
        private static Form1 _DefaultForm;
        /// <summary>
        /// </summary>
        public Form1()
        {
            this.InitializeComponent();
        }
        public static Form1 DefaultForm
        {
            get
            {
                if (((_DefaultForm == null) 
                            || (_DefaultForm.IsDisposed || _DefaultForm.Disposing)))
                {
                    _DefaultForm = new Form1();
                }
                return _DefaultForm;
            }
        }
        public virtual DefaultNamespace.Form2 Form22
        {
            get
            {
                if (((var16f4a848 == null) 
                            || (var16f4a848.IsDisposed == true)))
                {
                    var16f4a848 = new DefaultNamespace.Form2();
                }
                return var16f4a848;
            }
        }
        public virtual DefaultNamespace.Form3 Form32
        {
            get
            {
                if (((varc80ef335 == null) 
                            || (varc80ef335.IsDisposed == true)))
                {
                    varc80ef335 = new DefaultNamespace.Form3();
                }
                return varc80ef335;
            }
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.Label1 = new System.Windows.Forms.Label();
            this.Label2 = new System.Windows.Forms.Label();
            this.Label3 = new System.Windows.Forms.Label();
            this.Button1 = new System.Windows.Forms.Button();
            this.Button2 = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // Label1
            // 
            this.Label1.Font = new System.Drawing.Font("Algerian", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Label1.ForeColor = System.Drawing.SystemColors.Desktop;
            this.Label1.Location = new System.Drawing.Point(83, 27);
            this.Label1.Name = "Label1";
            this.Label1.Size = new System.Drawing.Size(98, 51);
            this.Label1.TabIndex = 0;
            this.Label1.Text = "        Welcome ";
            // 
            // Label2
            // 
            this.Label2.Font = new System.Drawing.Font("Lucida Handwriting", 12F, System.Drawing.FontStyle.Bold);
            this.Label2.ForeColor = System.Drawing.SystemColors.Desktop;
            this.Label2.Location = new System.Drawing.Point(50, 78);
            this.Label2.Name = "Label2";
            this.Label2.Size = new System.Drawing.Size(100, 23);
            this.Label2.TabIndex = 1;
            this.Label2.Text = "         To";
            // 
            // Label3
            // 
            this.Label3.Font = new System.Drawing.Font("Algerian", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Label3.ForeColor = System.Drawing.SystemColors.Desktop;
            this.Label3.Location = new System.Drawing.Point(26, 116);
            this.Label3.Name = "Label3";
            this.Label3.Size = new System.Drawing.Size(199, 30);
            this.Label3.TabIndex = 2;
            this.Label3.Text = "   G-Merchant App";
            // 
            // Button1
            // 
            this.Button1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Button1.Location = new System.Drawing.Point(26, 181);
            this.Button1.Name = "Button1";
            this.Button1.Size = new System.Drawing.Size(75, 35);
            this.Button1.TabIndex = 3;
            this.Button1.Text = "Login";
            this.Button1.UseVisualStyleBackColor = true;
            this.Button1.Click += new System.EventHandler(this.Click_ff3a87dd);
            // 
            // Button2
            // 
            this.Button2.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.Button2.Location = new System.Drawing.Point(164, 181);
            this.Button2.Name = "Button2";
            this.Button2.Size = new System.Drawing.Size(75, 35);
            this.Button2.TabIndex = 4;
            this.Button2.Text = "SignUp";
            this.Button2.UseVisualStyleBackColor = true;
            this.Button2.Click += new System.EventHandler(this.Click_cbc6cd36);
            // 
            // Form22
            // 
            this.Form22.LoginPage = null;
            this.Form22.PageAttributes.Height = 297D;
            this.Form22.PageAttributes.PageHeight = 1122.51968503937D;
            this.Form22.PageAttributes.PageWidth = 793.70078740157476D;
            this.Form22.PageAttributes.PrinterDPI_X = 96F;
            this.Form22.PageAttributes.PrinterDPI_Y = 96F;
            this.Form22.PageAttributes.ShowPrintPageEdges = false;
            this.Form22.PageAttributes.Width = 210D;
            this.Form22.Text = "DrawingPage";
            this.Form22.UserLevel = 0;
            this.Form22.Visible = false;
            // 
            // Form32
            // 
            this.Form32.LoginPage = null;
            this.Form32.PageAttributes.Height = 297D;
            this.Form32.PageAttributes.PageHeight = 1122.51968503937D;
            this.Form32.PageAttributes.PageWidth = 793.70078740157476D;
            this.Form32.PageAttributes.PrinterDPI_X = 96F;
            this.Form32.PageAttributes.PrinterDPI_Y = 96F;
            this.Form32.PageAttributes.ShowPrintPageEdges = false;
            this.Form32.PageAttributes.Width = 210D;
            this.Form32.Text = "DrawingPage";
            this.Form32.UserLevel = 0;
            this.Form32.Visible = false;
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.ClientSize = new System.Drawing.Size(282, 257);
            this.Controls.Add(this.Label1);
            this.Controls.Add(this.Label2);
            this.Controls.Add(this.Label3);
            this.Controls.Add(this.Button1);
            this.Controls.Add(this.Button2);
            this.DrawingLayerList = ((Limnor.Drawing2D.DrawingLayerHeaderList)(resources.GetObject("$this.DrawingLayerList")));
            this.Name = "Form1";
            this.Text = "Welcome";
            this.ResumeLayout(false);
        }
        private void Click_ff3a87dd(object sender, System.EventArgs e)
        {
            Form22.Show();
        }
        private void Click_cbc6cd36(object sender, System.EventArgs e)
        {
            Form32.Show();
        }
    }
}
